Reservation unit no longer reservable if no payment_product
City-of-Helsinki/tilavarauspalvelu-core pull request #1011
Opened 2023-12-08 08:37 UTC by matti-lamppu

## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- reservation_unit state is no longer RESERVABLE if it has no payment_product

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of what's the fastest way to test your changes."

- Automated tests

## 🎫 Tickets
[//]: # "This pull request resolves all or part of the following ticket(s)"

- [TILA-2944](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2944)

2023-12-08 09:56 UTC, vergama requested changes
Also need to check that the reservation unit needs payment, if it's free then the payment product is not needed.
Cf. [ReservationConfirmSerializer](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/blob/c958235e67f22ba101da6a6cc772daba96fe93b8/api/graphql/types/reservations/serializers/confirm_serializers.py#L81): `active_price.pricing_type == PricingType.PAID`

2023-12-08 10:16 UTC, matti-lamppu commented
> Also need to check that the reservation unit needs payment, if it's free then the payment product is not needed. Cf. [ReservationConfirmSerializer](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/blob/c958235e67f22ba101da6a6cc772daba96fe93b8/api/graphql/types/reservations/serializers/confirm_serializers.py#L81): `active_price.pricing_type == PricingType.PAID`

Would this be correct? @vergama 

```python
active_price = ReservationUnitPricingHelper.get_active_price(reservation_unit)

...

    (
        active_price is not None
        and active_price.pricing_type == PricingType.PAID
        and reservation_unit.payment_product is not None
    ) or (
        active_price is not None
        and active_price.pricing_type == PricingType.FREE
    )

```

2023-12-08 10:39 UTC, vergama commented
> Would this be correct? @vergama

Yeah that should do the trick.

2023-12-08 11:25 UTC, matti-lamppu commented
> > Would this be correct? @vergama
> 
> Yeah that should do the trick.

Fix in the newest commit.

2023-12-08 12:15 UTC, vergama requested changes
I now realised that:

1. `ReservationState.SCHEDULED_CLOSING` also allows reservations being made, so the same extra conditions can be added to it, too. (Currently reservable but the res.unit has an ending time set in the future.)
2. Furthermore, if paid res.units missing the payment product are excluded from that state and `RESERVABLE`, then they should be included in the scope of `RESERVATION_CLOSED` to avoid an unknown state (assuming that their time range would have otherwise resolved as `RESERVABLE` or `SCHEDULED_CLOSING` but not one of the other states).

However, part **2** might lead to unnecessarily complex conditions for the `RESERVATION_CLOSED` check... I suppose that state could instead just be the default, if nothing else matches; it would work out for the UI by (a) disallowing reservations unless conditions expressly allow them by another state (the two above), or (b) informing users that reservation will be possible after a future date (`SCHEDULED_RESERVATION`, `SCHEDULED_PERIOD`).

2023-12-12 07:16 UTC, matti-lamppu commented
Should be finally fixed now. Refactored tests and added documentation diagrams.

2023-12-12 15:00 UTC, vergama commented on reservation_units/utils/reservation_unit_reservation_state_helper.py
> +            # and end in the past, but begin before they end
Typo here: `but begin before they end` => `but begin (again) after they end`

2023-12-12 15:01 UTC, vergama requested changes
Nice! Just one typofix to a single comment line needed.

2023-12-13 07:31 UTC, matti-lamppu commented on reservation_units/utils/reservation_unit_reservation_state_helper.py
> +            # and end in the past, but begin before they end
Fxed

2023-12-13 07:40 UTC, vergama approved these changes

2023-12-13 07:44 UTC, merged