Refactor settings
City-of-Helsinki/tilavarauspalvelu-core pull request #1178
Opened 2024-04-29 13:21 UTC by matti-lamppu

## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Refactors how the project's settings are defined
    - Use [django-environment-config](https://github.com/MrThearMan/django-environment-config) for configuring how different environments are set up (at first, I tried using [django-configurations](https://github.com/jazzband/django-configurations), but I wasn't too happy with how [magical it was](https://github.com/jazzband/django-configurations/issues/360), [so I decided to write my own](https://xkcd.com/927/))
- Some small refactorings

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests
- Backend devs should check that it works locally following the setup
- Frontend devs should check that the docker setup works for them

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

2024-04-30 09:51 UTC, matti-lamppu commented
This requires testing in Platta to check that all environment variables are in there. Note that all environments should be checked, or at least their variables.

2024-05-06 15:26 UTC, ranta requested changes
Really nice work 🚀 

Discussed some issues off-platform, which should be addressed before merging

2024-05-07 08:40 UTC, matti-lamppu commented on README.md
> +These can be used to override settings for local development and automated tests respectively.
Fixed.

2024-05-08 12:55 UTC, ranta approved these changes
# Magical 🧙🪄

2024-06-04 07:38 UTC, matti-lamppu commented
/fast-forward

2024-06-04 07:38 UTC, merged