Convert Reservation net price fields into properties
City-of-Helsinki/tilavarauspalvelu-core pull request #1304
Opened 2024-08-28 13:54 UTC by ranta

## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Convert Reservation net price fields into properties
- This should not require changes from the frontend, as the fields should be simply ignored if they are sent

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests
- Might be good to manually test as well just in case :D

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

## 🎫 Tickets
[//]: # "This pull request resolves all or part of the following ticket(s)."

- [TILA-3485](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3485)

2024-08-28 15:05 UTC, matti-lamppu approved these changes

2024-08-30 06:57 UTC, vergama commented on reservations/models/reservation.py
> +        return round_decimal(self.price / (1 + self.tax_percentage_value / Decimal(100)), 6)
I think we can round to the usual 2 decimal places when this is now an ephemeral and no longer a stored value.

2024-08-30 06:59 UTC, vergama commented on reservations/models/reservation.py
> +        return round_decimal(self.non_subsidised_price / (1 + self.tax_percentage_value / Decimal(100)), 6)
Same as above with the (subsidised) net price, 2 decimal prices would be appropriate.

2024-08-30 07:13 UTC, vergama commented on merchants/verkkokauppa/helpers.py
> +    price_net = round_decimal(quantity * reservation.price_net, 2)
The formula should be:
1. gross price = quantity * reservation.price # e.g. 1 * 123.45 €
2. net price = round_decimal(gross price / (1 + reservation.tax_percentage_value / 100), 2) # e.g. 123.45 / 1.255 = 98.366... ~= 98.37 € -- or in practice reservation.price_net as long as quantity is always 1
3. vat amount = gross - net price # e.g. 123.45 - 98.37 = 25.08 €

2024-08-30 07:17 UTC, vergama requested changes
Two comments: these go back to the old code but let's fix them now.

2024-09-06 07:06 UTC, vergama approved these changes

2024-09-12 05:14 UTC, merged