Generate PDF for booking terms
City-of-Helsinki/tilavarauspalvelu-core pull request #1333
Opened 2024-09-13 13:29 UTC by matti-lamppu

## 🛠️ Changelog
[//]: # "Describe the changes in this pull request here."

- Add endpoint for generating and downloading booking terms PDF
- Add option to admin panel for showing current PDF in browser
- Example file: [Tilavarauspalvelu_yleiset_sopimusehdot - generoitu.pdf](https://github.com/user-attachments/files/16994541/Tilavarauspalvelu_yleiset_sopimusehdot.-.generoitu.pdf)

## 🧪 Test plan
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your changes."

- Automated tests

## 🚧 Dependencies
[//]: # "Is this PR dependent on other changes outside this repository? Describe the changes, or add links to them."
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before merging."

- None

## 🎫 Tickets
[//]: # "This pull request resolves all or part of the following ticket(s)."

- [TILA-3416](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3416)

2024-09-16 11:00 UTC, vergama commented on terms_of_use/templates/terms_of_use/components/base.jinja
> +      {% set government_heading = 'Central government' %}
Looks like the term which is used in EN translation is 'Central Administration'
Cf. e.g. https://www.hel.fi/en/decision-making/city-organisation/divisions

2024-09-16 11:11 UTC, vergama requested changes
Good to go, the only thing I noticed is the one translation.

2024-09-16 11:26 UTC, vergama approved these changes

2024-09-16 12:15 UTC, ranta approved these changes
Really clean implementation 🚀 

I didn't realise we didn't already have jinja installed 😱 I have been using its features already without issues 😅

2024-09-17 05:19 UTC, matti-lamppu commented
@ranta We did have `jinja` installed, but not `django-jinja`. The latter includes some adapter logic for templating which is not available in django itself, and was required by the PDF converter.

2024-09-18 11:05 UTC, merged