TILA-1606 | Standardized graphql query optimization
City-of-Helsinki/tilavarauspalvelu-core pull request #521
Opened 2022-05-24 15:01 UTC by Niilis

Standardized utils function to optimize GraphQL queries dynamically.

Applied query optimizer for applications field as an example and testing field.

2022-05-27 15:43 UTC, nicobav requested changes
Looks great :+1: 

Only some line breaks to get rid off :shrug:

2022-05-27 15:43 UTC, nicobav commented on utils/query_performance.py
> +
I'd get rid off the air here

2022-05-27 15:43 UTC, nicobav commented on utils/query_performance.py
> +
I'd get rid off the air here

2022-05-27 15:43 UTC, nicobav commented on utils/query_performance.py
> +
I'd get rid off the air here

2022-06-03 10:24 UTC, nicobav approved these changes
amazing!

2022-06-06 06:04 UTC, saaste approved these changes
Took me a while to understand all the bells and whistles and I still don't quite comprehend everything - mostly because of my tiny Django experience. But the code is easy to read and follow and in general it makes sense.

So, LGTM!

I wonder if something like this has been already done and provided as a package. This feels such a common problem that one would think that we can't been the only one struggling with query optimization 😄

2022-06-07 06:43 UTC, Niilis commented
> Took me a while to understand all the bells and whistles and I still don't quite comprehend everything - mostly because of my tiny Django experience. But the code is easy to read and follow and in general it makes sense.
> 
> So, LGTM!
> 
> I wonder if something like this has been already done and provided as a package. This feels such a common problem that one would think that we can't been the only one struggling with query optimization smile

@saaste there is this one [Graphene Django query optimizer](https://github.com/tfoxy/graphene-django-optimizer), but I did not get it to work on deeper levels than 1-2. Within this project, some structures are many levels more deep and will definitely clog servers with the right kind of a query. That is why this PR was created as this does recognize deeper levels and includes the necessary defined optimizations.

2022-06-07 07:00 UTC, merged