TILA-1635: Allow reservations without opening hours
City-of-Helsinki/tilavarauspalvelu-core pull request #524
Opened 2022-05-25 13:40 UTC by saaste

The PR adds a new boolean flag to `ReservationUnit`. If the flag is set true, reservations can be done without opening hours.

I'm still lacking a lot of context so it is quite likely that not everything I did might make sense 😅  Take extra care when reviewing this PR and feel free to add as many comments as needed to address all the issues. I'll check them out on Monday ☺️

2022-05-27 09:18 UTC, nicobav requested changes
Looks good overall, some cleanup things mostly :+1: 

You also need to rebase with main and resolve conflicts and  also re-create the migration file since in the main there is now already migration file in reservation_units with number 0056 in it.

2022-05-27 09:18 UTC, nicobav commented on api/graphql/reservations/reservation_serializers.py
> +        if reservation_unit.allow_reservations_without_opening_hours:
returning here will mean we don't check `reservation_begins` dates and not check the overlap.

So I would remove this and add a condition in the `is_reservation_unit_open` like:
```
is_reservation_unit_open = reservation_unit.allow_reservations_without_opening_hours or scheduler.is_reservation_unit_open(begin, end)
```

But this thing should perhaps have its own method where no other than opening hour related would be checked (refs the above comment)

2022-05-27 09:18 UTC, nicobav commented on api/graphql/reservation_units/reservation_unit_serializers.py.orig
> +from django.core import validators
This file is probably some leftover from gitting and should get deleted

2022-05-27 09:18 UTC, nicobav commented on api/graphql/reservation_units/reservation_unit_types.py.orig
> +import datetime
This file is probably some leftover from gitting and should get deleted

2022-05-27 09:18 UTC, nicobav commented on api/graphql/tests/test_reservation_units.py.orig
> +import datetime
This file is probably some leftover from gitting and should get deleted

2022-05-27 09:18 UTC, nicobav commented on reservation_units/models.py.orig
> +import datetime
This file is probably some leftover from gitting and should get deleted

2022-05-27 09:18 UTC, nicobav commented on tilavarauspalvelu_visualized.json.orig
> +<<<<<<< HEAD
This file is probably some leftover from gitting and should get deleted

2022-05-27 09:18 UTC, nicobav commented on api/graphql/reservation_units/reservation_unit_serializers.py
> +        help_text="Allow reservations without opening hours. Used for testing.",
This rename commit should be rebased into the original commit where this field was introduced to avoid code churn

2022-05-30 09:43 UTC, saaste commented
I close this one. #526 has much cleaner commit history.

2022-05-30 09:43 UTC, closed without merging