TILA-1691: Allow sorting units by name
City-of-Helsinki/tilavarauspalvelu-core pull request #528
Opened 2022-06-01 05:58 UTC by saaste

Adds `UnitsFiltersSet` and enables sorting `Unit` by name. I also added some tests to cover basic query cases.

2022-06-01 18:10 UTC, nicobav requested changes
Very nice :ok_hand: 
Only my vainglorius nitpicks about :nerd_face:

2022-06-02 03:14 UTC, saaste commented on api/graphql/tests/test_units.py
>          cls.unit = UnitFactory()
Good idea! I added some 🍖

2022-06-02 03:15 UTC, saaste commented on api/graphql/tests/test_units.py
> +    def test_getting_units(self):
Now it is split into two ☺️

2022-06-02 06:03 UTC, nicobav approved these changes
Awesome :metal:

2022-06-02 06:07 UTC, merged