TILA-1692: Add pricing terms and pricing type to reservation unit
City-of-Helsinki/tilavarauspalvelu-core pull request #545
Opened 2022-06-20 06:43 UTC by saaste

- Add pricing terms to Reservation Unit
- Add TERMS_TYPE_PRICING to TermsOfUse
- Add pricing type to Reservation Unit
- Update TermsOfUse admin view to support rich text editing
- Update visualization

2022-06-20 09:05 UTC, nicobav requested changes

2022-06-21 03:40 UTC, saaste commented on reservation_units/models.py
> +    PAID = "paid", _("Paid")
Oh, okay! I just copied to code from `ReservationKind` above 😄

2022-06-23 08:18 UTC, nicobav commented on reservation_units/models.py
> +    DIRECT = "direct"
Nice one :+1:

2022-06-23 08:19 UTC, nicobav approved these changes
:shipit: 
![](https://media.giphy.com/media/10RgsuetO4uDkY/giphy.gif)

2022-06-27 05:03 UTC, merged