TILA-1768 - Add reservation unit qualifier
City-of-Helsinki/tilavarauspalvelu-core pull request #567
Opened 2022-08-02 06:29 UTC by saaste

Added a new qualifier model with many-to-many relationship to Reservation Unit.
- Reservation units can be filtered with qualifier IDs
- GraphQL API allows querying qualifiers

⚠️ **DO NOT MERGE** ⚠️
For some reason model visualization test broke. I couldn't make it work with updated visualization. I disabled the test for now, but this needs to be fixed before merging.

2022-08-09 12:11 UTC, nicobav requested changes

2022-08-09 12:11 UTC, nicobav commented on api/graphql/tests/test_qualifiers.py
> +class PurposeQueryTestCase(GrapheneTestCaseBase, snapshottest.TestCase):
`QualifierQueryTestCase`

2022-08-10 03:09 UTC, saaste commented on api/graphql/tests/test_qualifiers.py
> +class PurposeQueryTestCase(GrapheneTestCaseBase, snapshottest.TestCase):
Copy-paste monster attacks! Fix'd!

2022-08-10 03:10 UTC, saaste commented
I fixed the wrong test name, solved the migration filename mayhem that was a result of merge conflict.

2022-08-10 06:28 UTC, nicobav approved these changes

2022-08-11 03:23 UTC, merged