TILA-1765: Calculate reservation price on create/update
City-of-Helsinki/tilavarauspalvelu-core pull request #570
Opened 2022-08-05 10:34 UTC by saaste

The logic of the calculation is described in [TILA-1765](https://helsinkisolutionoffice.atlassian.net/browse/TILA-1765). When reservation is updated, price is calculated only if begin or end time is updated or when reservation units are changed.

2022-08-10 08:36 UTC, nicobav requested changes

2022-08-10 08:36 UTC, nicobav commented on api/graphql/reservations/reservation_serializers.py
> +            # If unit is not paid, there is no need for calculations. Skip.
This wording can confuse: "If unit is not paid,". I suggest changing it to "If unit pricing type is not PAID,"

2022-08-11 04:56 UTC, saaste commented on api/graphql/reservations/reservation_serializers.py
> +    reservation_price: Decimal = 0.0
Oh, crap! I'm still in statically typed world 😄 Fixed!

2022-08-11 06:50 UTC, nicobav approved these changes
LGTM :rocket:

2022-08-11 06:54 UTC, nicobav commented on api/graphql/reservations/reservation_serializers.py
> +    reservation_price: Decimal = 0.0
And I seem to stutter also when I write :sweat_smile:

2022-08-11 06:55 UTC, nicobav commented on api/graphql/reservations/reservation_serializers.py
> +    reservation_price: Decimal = 0.0
> though using the the type declaration

2022-08-11 07:13 UTC, merged