TILA-2379: Refund webhook endpoint
City-of-Helsinki/tilavarauspalvelu-core pull request #770
Opened 2023-03-03 04:38 UTC by saaste

## Change log
- Added missing configs to `.env.example`
- Added a new endpoint that handles refund webhooks from Verkkokauppa

## Notes
Our model is still missing a field that is required a bit later. I left a TODO comment for this. There is already task for it.

## Deployment reminder
- No changes required

2023-03-07 07:50 UTC, nicobav requested changes

2023-03-08 03:24 UTC, saaste commented on api/webhook_api/views.py
> +        type = request.data.get("type", None)
Renamed to `webhook_type` 👍

2023-03-08 03:25 UTC, saaste commented on api/webhook_api/views.py
> +            # refund_id = request.data.get("refundId", "")
Cleaned 🧹

2023-03-08 03:31 UTC, saaste commented
Checks fails because of outdated Django with CVE. #773 has the update so I'll retry the checks once that is merged.

2023-03-08 09:49 UTC, nicobav approved these changes
👍

2023-03-08 09:50 UTC, merged